export const CARREGAR_CASOS_FACTORY = 'CARREGAR_CASOS_FACTORY'
export const CARREGAR_DADOS_VACINACAO_FACTORY = 'CARREGAR_DADOS_VACINACAO_FACTORY'
export const CARREGAR_ESTADOS_FACTORY = 'CARREGAR_ESTADOS_FACTORY'